### ISSUE TITLE
Error compiling ip2unix 2.2.1: "FAILED: src/errno_list.cc" and "ccache: invalid option -- 'E'"

### ISSUE THREAD

**Issue by przemyslaw0** [nixcloud/ip2unix#36]
I tried to compile ip2unix but I can't:

```
$ meson build
The Meson build system
Version: 1.4.1
Source dir: /dev/shm/ip2unix
Build dir: /dev/shm/ip2unix/build
Build type: native build
Project name: ip2unix
Project version: 2.2.1
C++ compiler for the host machine: ccache c++ (gcc 13.2.0 "c++ (Debian 13.2.0-25) 13.2.0")
C++ linker for the host machine: c++ ld.bfd 2.42
Host machine cpu family: x86_64
Host machine cpu: x86_64
Checking if "std::filesystem works" runs: YES
Compiler for C++ supports arguments -Wcast-qual: YES 
Compiler for C++ supports arguments -Wcovered-switch-default: NO 
Compiler for C++ supports arguments -Weffc++: YES 
Compiler for C++ supports arguments -Wextra-semi: YES 
Compiler for C++ supports arguments -Wimplicit-fallthrough: YES 
Compiler for C++ supports arguments -Wno-trigraphs: YES 
Compiler for C++ supports arguments -Wold-style-cast: YES 
Compiler for C++ supports arguments -Wrange-loop-analysis: NO 
Compiler for C++ supports arguments -Wreserved-id-macro: NO 
Compiler for C++ supports arguments -Wshadow: YES 
Compiler for C++ supports arguments -Wsign-conversion: YES 
Compiler for C++ supports arguments -Wswitch-enum: YES 
Compiler for C++ supports arguments -Wunused-exception-parameter: NO 
Compiler for C++ supports arguments -Wuseless-cast: YES 
Compiler for C++ supports arguments -Wzero-as-null-pointer-constant: YES 
Program python3 found: YES (/usr/bin/python3)
Found pkg-config: YES (/usr/bin/pkg-config) 1.8.1
Run-time dependency yaml-cpp found: YES 0.8.0
Library dl found: YES
Header "sys/epoll.h" has symbol "epoll_ctl" : YES 
Program a2x found: YES (/usr/bin/a2x)
Program xsltproc found: YES (/usr/bin/xsltproc)
Program xmllint found: YES (/usr/bin/xmllint)
Program pytest-3 found: YES (/usr/bin/pytest-3)
Program systemd-socket-activate found: YES (/usr/bin/systemd-socket-activate)
Build targets in project: 11
NOTICE: Future-deprecated features used:
 * 0.55.0: {'ExternalProgram.path'}

Found ninja-1.12.1 at /usr/bin/ninja
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
$ ninja -C build
ninja: Entering directory `build'
[2/38] Generating src/errno_list with a custom command (wrapped by meson to capture output)
FAILED: src/errno_list.cc 
/usr/bin/meson --internal exe --capture src/errno_list.cc -- /usr/bin/python3 ../scripts/generrno.py ccache c++
--- stderr ---
ccache: invalid option -- 'E'
Traceback (most recent call last):
  File "/dev/shm/ip2unix/build/../scripts/generrno.py", line 6, in <module>
    macros = subprocess.check_output(cmd, input=b'')
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ccache', '-E', '-dM', '-include', 'errno.h', '-']' returned non-zero exit status 1.

[7/38] Compiling C++ object libip2unix.so.p/meson-generated_.._src_dynports.cc.o
ninja: build stopped: subcommand failed.
```

Meson version:
$ meson -v
1.4.1

Ninja version:
$ ninja --version
1.12.1

**Comment by aszlig** [comment]
What is the value of the `$CC` and `$CXX` environment variables?
